---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresq-config
data:
  POSTRES_DB: mydb
  POSTGRES_USER: root
  POSTGRES_PASSWORD: password
